//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Downwork_Notifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Downwork_Notifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token.
        /// </summary>
        public static string ACCESS_TOKEN_LBL {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token secret.
        /// </summary>
        public static string ACCESS_TOKEN_SECRET_LBL {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_SECRET_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downwork Notifier.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: {0}.
        /// </summary>
        public static string CLIENT_COUNTRY_SF {
            get {
                return ResourceManager.GetString("CLIENT_COUNTRY_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Feedback.
        /// </summary>
        public static string CLIENT_FEEDBACK_LBL {
            get {
                return ResourceManager.GetString("CLIENT_FEEDBACK_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback: {0}.
        /// </summary>
        public static string CLIENT_FEEDBACK_SF {
            get {
                return ResourceManager.GetString("CLIENT_FEEDBACK_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Hires.
        /// </summary>
        public static string CLIENT_HIRES_LBL {
            get {
                return ResourceManager.GetString("CLIENT_HIRES_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (hired: {0}).
        /// </summary>
        public static string CLIENT_HIRES_SF {
            get {
                return ResourceManager.GetString("CLIENT_HIRES_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs posted: {0}.
        /// </summary>
        public static string CLIENT_JOBS_POSTED_SF {
            get {
                return ResourceManager.GetString("CLIENT_JOBS_POSTED_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment: {0}.
        /// </summary>
        public static string CLIENT_PAYMENT_STATUS_SF {
            get {
                return ResourceManager.GetString("CLIENT_PAYMENT_STATUS_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} reviews).
        /// </summary>
        public static string CLIENT_REVIEWS_COUNT_SF {
            get {
                return ResourceManager.GetString("CLIENT_REVIEWS_COUNT_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ENUM_Duration_Month {
            get {
                return ResourceManager.GetString("ENUM_Duration_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ENUM_Duration_None {
            get {
                return ResourceManager.GetString("ENUM_Duration_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string ENUM_Duration_Ongoing {
            get {
                return ResourceManager.GetString("ENUM_Duration_Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string ENUM_Duration_Quarter {
            get {
                return ResourceManager.GetString("ENUM_Duration_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string ENUM_Duration_Semester {
            get {
                return ResourceManager.GetString("ENUM_Duration_Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string ENUM_Duration_Week {
            get {
                return ResourceManager.GetString("ENUM_Duration_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string ENUM_JobStatus_Cancelled {
            get {
                return ResourceManager.GetString("ENUM_JobStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ENUM_JobStatus_Completed {
            get {
                return ResourceManager.GetString("ENUM_JobStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ENUM_JobStatus_None {
            get {
                return ResourceManager.GetString("ENUM_JobStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ENUM_JobStatus_Open {
            get {
                return ResourceManager.GetString("ENUM_JobStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed price.
        /// </summary>
        public static string ENUM_JobType_FixedPrice {
            get {
                return ResourceManager.GetString("ENUM_JobType_FixedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        public static string ENUM_JobType_Hourly {
            get {
                return ResourceManager.GetString("ENUM_JobType_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ENUM_JobType_None {
            get {
                return ResourceManager.GetString("ENUM_JobType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As needed.
        /// </summary>
        public static string ENUM_Workload_AsNeeded {
            get {
                return ResourceManager.GetString("ENUM_Workload_AsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time.
        /// </summary>
        public static string ENUM_Workload_FullTime {
            get {
                return ResourceManager.GetString("ENUM_Workload_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ENUM_Workload_None {
            get {
                return ResourceManager.GetString("ENUM_Workload_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part time.
        /// </summary>
        public static string ENUM_Workload_PartTime {
            get {
                return ResourceManager.GetString("ENUM_Workload_PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename tab.
        /// </summary>
        public static string FILTER_EDIT_TIP {
            get {
                return ResourceManager.GetString("FILTER_EDIT_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills list isn&apos;t loaded. Try refresh.
        /// </summary>
        public static string FILTER_EMPTY_SKILLS_LBL {
            get {
                return ResourceManager.GetString("FILTER_EMPTY_SKILLS_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Filter.
        /// </summary>
        public static string FILTER_NEW_FILTER_NAME {
            get {
                return ResourceManager.GetString("FILTER_NEW_FILTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tab.
        /// </summary>
        public static string FILTER_NEW_TIP {
            get {
                return ResourceManager.GetString("FILTER_NEW_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query.
        /// </summary>
        public static string FILTER_QUERY_LBL {
            get {
                return ResourceManager.GetString("FILTER_QUERY_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tab.
        /// </summary>
        public static string FILTER_REMOVE_TIP {
            get {
                return ResourceManager.GetString("FILTER_REMOVE_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected skills.
        /// </summary>
        public static string FILTER_SELECTED_SKILLS_LBL {
            get {
                return ResourceManager.GetString("FILTER_SELECTED_SKILLS_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup filter for searching.
        /// </summary>
        public static string FILTER_SETTINGS_LBL {
            get {
                return ResourceManager.GetString("FILTER_SETTINGS_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string FILTER_SKILLS_LBL {
            get {
                return ResourceManager.GetString("FILTER_SKILLS_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string FILTER_TITLE_LBL {
            get {
                return ResourceManager.GetString("FILTER_TITLE_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear jobs on tab.
        /// </summary>
        public static string FILTER_TRASH_TIP {
            get {
                return ResourceManager.GetString("FILTER_TRASH_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_TRAY_ACTIVE {
            get {
                object obj = ResourceManager.GetObject("ICON_TRAY_ACTIVE", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON_TRAY_DEACTIVATED {
            get {
                object obj = ResourceManager.GetObject("ICON_TRAY_DEACTIVATED", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string JOB_BUDGET_LBL {
            get {
                return ResourceManager.GetString("JOB_BUDGET_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        public static string JOB_CATEGORY_LBL {
            get {
                return ResourceManager.GetString("JOB_CATEGORY_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Data.
        /// </summary>
        public static string JOB_CREATED_DATE_LBL {
            get {
                return ResourceManager.GetString("JOB_CREATED_DATE_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string JOB_DURATION_LBL {
            get {
                return ResourceManager.GetString("JOB_DURATION_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills: {0}.
        /// </summary>
        public static string JOB_SKILLS_SF {
            get {
                return ResourceManager.GetString("JOB_SKILLS_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string JOB_STATUS_LBL {
            get {
                return ResourceManager.GetString("JOB_STATUS_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string JOB_TITLE_LBL {
            get {
                return ResourceManager.GetString("JOB_TITLE_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string JOB_TYPE_LBL {
            get {
                return ResourceManager.GetString("JOB_TYPE_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload.
        /// </summary>
        public static string JOB_WORKLOAD_LBL {
            get {
                return ResourceManager.GetString("JOB_WORKLOAD_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs found: {0}.
        /// </summary>
        public static string JOBS_FOUND_LBL_SF {
            get {
                return ResourceManager.GetString("JOBS_FOUND_LBL_SF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LOGIN_BTN {
            get {
                return ResourceManager.GetString("LOGIN_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is found!.
        /// </summary>
        public static string MSG_ACCESS_TOKEN_FOUND {
            get {
                return ResourceManager.GetString("MSG_ACCESS_TOKEN_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization with API failed..
        /// </summary>
        public static string MSG_API_AUTHORIZE_FAIL {
            get {
                return ResourceManager.GetString("MSG_API_AUTHORIZE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully authorized with API..
        /// </summary>
        public static string MSG_API_AUTHORIZE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_API_AUTHORIZE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize API and connection to it..
        /// </summary>
        public static string MSG_API_INITIALIZE {
            get {
                return ResourceManager.GetString("MSG_API_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to authorize with API..
        /// </summary>
        public static string MSG_API_TRY_AUTHORIZE {
            get {
                return ResourceManager.GetString("MSG_API_TRY_AUTHORIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata loaded from API. Categories found: {CATEGORIES_CNT}. Skills found: {SKILLS_CNT}.
        /// </summary>
        public static string MSG_METADATA_LOADED {
            get {
                return ResourceManager.GetString("MSG_METADATA_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading metadata from API..
        /// </summary>
        public static string MSG_METADATA_LOADING {
            get {
                return ResourceManager.GetString("MSG_METADATA_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New jobs are found.
        /// </summary>
        public static string MSG_POPUP_JOB_FOUND {
            get {
                return ResourceManager.GetString("MSG_POPUP_JOB_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Filter.
        /// </summary>
        public static string NEW_FILTER_TEXT {
            get {
                return ResourceManager.GetString("NEW_FILTER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable popups.
        /// </summary>
        public static string POPUPS_ENABLE_LBL {
            get {
                return ResourceManager.GetString("POPUPS_ENABLE_LBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to display a popup (sec).
        /// </summary>
        public static string POPUPS_TIME_TIP {
            get {
                return ResourceManager.GetString("POPUPS_TIME_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start searching.
        /// </summary>
        public static string SEARCH_BTN {
            get {
                return ResourceManager.GetString("SEARCH_BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TRAY_CLOSE {
            get {
                return ResourceManager.GetString("TRAY_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string TRAY_OPEN {
            get {
                return ResourceManager.GetString("TRAY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh jobs.
        /// </summary>
        public static string TRAY_REFRESH {
            get {
                return ResourceManager.GetString("TRAY_REFRESH", resourceCulture);
            }
        }
    }
}
